default_language_version:
  python: python3

repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
  - id: black
    args: [--line-length=79]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      files: ^tiny_blocks/
      args: [--no-strict-optional, --ignore-missing-imports]
