version: "3.3"
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

#  minio:
#    image: minio/minio:latest
#    ports:
#      - '9000:9000'
#      - '9001:9001'
#    environment:
#      - MINIO_ACCESS_KEY=access-key
#      - MINIO_SECRET_KEY=secret-key
#      - CONSOLE_ACCESS_KEY=test
#      - CONSOLE_SECRET_KEY=test
#    command: server --address ":9000" --console-address ":9001" /data
#    volumes:
#      - ./data:/code/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - SHELL=/bin/bash
    ports:
      - "8888:8888"  # for jupyter notebooks
    volumes:
      - ./:/code
