version: '3.3'
services:

  mysqldb:
    image: mysql:latest
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=$PYTHONPATH:/code
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - SHELL=/bin/bash
    ports:
      - "8888:8888"  # for jupyter notebooks
    volumes:
      - ./:/code
