name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build docker
        run: docker-compose build app

      - name: Install python packages
        run: docker-compose run --rm app poetry install

      - name: Check your installed dependencies for security vulnerabilities
        run: docker-compose run --rm app poetry check

      - name: Test
        run: docker-compose run --rm app poetry run pytest

      - name: Flake8
        run: if docker-compose run --rm app poetry run flake8 tiny_blocks > flake8.txt; then echo 'flake8 is a success'; else cat flake8.txt; false; fi
